version: "3"

services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "10004:10004"
    depends_on:
      - syncslot_db
    networks:
      - syncslot_network

  syncslot_db:
    image: postgres:17.1
    container_name: "syncslot_db"
    hostname: 'db'
    volumes:
      - syncslot_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_DB: syncslot_db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"
    networks:
      - syncslot_network

volumes:
  syncslot_data:

networks:
  syncslot_network:
    driver: bridge
