"""company_name_password_made_not_unique

Revision ID: da05e91b96c9
Revises: e51f0633439b
Create Date: 2025-12-20 16:10:46.851418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da05e91b96c9'
down_revision: Union[str, Sequence[str], None] = 'e51f0633439b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_company_name'), 'company', type_='unique')
    op.drop_constraint(op.f('uq_company_password'), 'company', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_company_password'), 'company', ['password'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_company_name'), 'company', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
